[package]
name = "wasmer/python-flask-server"
version = "0.1.4"
description = "wasmer/python-flask-server py worker"
repository = "https://github.com/wasmerio/python-flask-example"
readme = "README.md"

[dependencies]
"python/python" = "^0.2.0"

[fs]
"/src" = "./src"
"/cpython/lib/python3.12" = "./.env/lib/python3.11"

[[command]]
name = "script"
module = "python/python:python"
runner = "wasi"

[command.annotations.wasi]
main-args = [
    "-m",
    "flask",
    "--app",
    "/src/main",
    "run",
    "--port=8080",
    "--debug",
    "--no-reload",
]
env = ["PYTHONEXECUTABLE: /bin/python"]
